[package]
name = "tern"
description = "A fast, low-memory SSH terminal"
version.workspace = true
edition.workspace = true
license.workspace = true
rust-version.workspace = true

[dependencies]
anyhow = "1"
gpui = { package = "gpui-pre", version = "=0.3.8" }
nucleo-matcher = "0.3"
serde = { version = "1", features = ["derive"] }
serde_json = "1"
thiserror = "2"
unicode-segmentation = "1"
gpui_platform = { package = "gpui-pre-platform", version = "=0.3.8", features = ["font-kit", "runtime_shaders"] }
tern-ssh.workspace = true
tern-term.workspace = true
tern-sync.workspace = true
tern-vault.workspace = true
base64 = "0.22"
ureq.workspace = true
image.workspace = true
tokio = { version = "1", features = ["rt-multi-thread"] }
tracing = "0.1"
tracing-appender = "0.2"
tracing-subscriber = { version = "0.3", default-features = false, features = ["fmt", "json", "env-filter", "registry"] }
portable-pty = "0.9.0"
async-channel = "2"
strip-ansi-escapes = "0.2.1"

[target.'cfg(target_os = "macos")'.dependencies]
objc2-app-kit = { version = "0.3.2", default-features = false, features = ["std", "NSWorkspace", "NSAccessibility"] }

[dev-dependencies]
tempfile = "3"

[lints]
workspace = true
