#!/usr/bin/env bash
# Rebuilds crates/tern/assets/themes.txt from iTerm2-Color-Schemes (MIT), Ghostty format.
# Usage: scripts/import-themes.sh <path to a clone of mbadolato/iTerm2-Color-Schemes>
set -euo pipefail
src=${1:?clone path}/ghostty
out=crates/tern/assets/themes.txt
{
  echo "# Generated by scripts/import-themes.sh from mbadolato/iTerm2-Color-Schemes (MIT)."
  for f in "$src"/*; do
    echo "## $(basename "$f")"
    grep -E '^(palette|background|foreground|cursor-color|selection-background) *=' "$f" | tr -d ' '
  done
} > "$out"
echo "$(grep -c '^## ' "$out") themes → $out"
